import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>耦左 ｜ Odore</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
    </>
  )
}
